"""Export the approved domain contracts to contracts/domain-contracts.json.

The JSON snapshot is shared with the frontend and checked by tests on both
sides, so accidental changes to approved states are detected.

    python -m app.domain.contracts_export          # write snapshot
    python -m app.domain.contracts_export --check  # exit 1 if snapshot is stale
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from app.domain import enums
from app.domain.inputs import MAX_CLAIM_CHARS, MAX_EXTRACTION_INPUT_CHARS, MAX_REVIEW_CLAIMS
from app.domain.trusted_sources import TRUSTED_SOURCES, Provider, TrustedSourceId

SNAPSHOT_PATH = Path(__file__).resolve().parents[3] / "contracts" / "domain-contracts.json"

_EXPORTED_ENUMS = {
    "ClaimType": enums.ClaimType,
    "ExtractionStatus": enums.ExtractionStatus,
    "UserConfirmationStatus": enums.UserConfirmationStatus,
    "ProvidedEvidenceType": enums.ProvidedEvidenceType,
    "SourceType": enums.SourceType,
    "AsbabRelationType": enums.AsbabRelationType,
    "QuranTextForm": enums.QuranTextForm,
    "RetrievalChannel": enums.RetrievalChannel,
    "RetrievalMatchBasis": enums.RetrievalMatchBasis,
    "SourceAvailability": enums.SourceAvailability,
    "RetrievalMethod": enums.RetrievalMethod,
    "EvidenceRelationship": enums.EvidenceRelationship,
    "VerificationStatus": enums.VerificationStatus,
    "EvidenceStrengthSignal": enums.EvidenceStrengthSignal,
    "ValidationOutcome": enums.ValidationOutcome,
    "ValidationCheck": enums.ValidationCheck,
    "RetryReason": enums.RetryReason,
    "OutOfScopeReason": enums.OutOfScopeReason,
    "SystemErrorCode": enums.SystemErrorCode,
    "ResultGroup": enums.ResultGroup,
    "CheckMode": enums.CheckMode,
    "InputType": enums.InputType,
    "PipelineStage": enums.PipelineStage,
    "Provider": Provider,
    "TrustedSourceId": TrustedSourceId,
}


def build_contracts() -> dict:
    return {
        "_comment": "GENERATED by `python -m app.domain.contracts_export`. Do not edit by hand.",
        "enums": {name: [m.value for m in e] for name, e in _EXPORTED_ENUMS.items()},
        "claimOutcomeKinds": [
            "verification",
            "out_of_scope",
            "system_error",
            "required_source_unavailable",
        ],
        "limits": {
            "claimExtractionMaxInputChars": MAX_EXTRACTION_INPUT_CHARS,
            "claimMaxChars": MAX_CLAIM_CHARS,
            "maxReviewClaims": MAX_REVIEW_CLAIMS,
        },
        "trustedSources": [
            {
                "id": s.id.value,
                "name_ar": s.name_ar,
                "provider": s.provider.value,
                "source_type": s.source_type.value,
                "qualified_for": sorted(c.value for c in s.qualified_for),
                "availability": s.availability.value,
                "quranpedia_mushaf_id": s.quranpedia_mushaf_id,
                "quranpedia_book_id": s.quranpedia_book_id,
            }
            for s in TRUSTED_SOURCES.values()
        ],
    }


def render() -> str:
    return json.dumps(build_contracts(), ensure_ascii=False, indent=2) + "\n"


def main(argv: list[str]) -> int:
    content = render()
    if "--check" in argv:
        current = SNAPSHOT_PATH.read_text(encoding="utf-8") if SNAPSHOT_PATH.exists() else ""
        if current != content:
            print(f"Contract snapshot is stale: {SNAPSHOT_PATH}", file=sys.stderr)
            return 1
        print("Contract snapshot is up to date.")
        return 0
    SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
    SNAPSHOT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {SNAPSHOT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
